class ApiEndPointsResponse {
  String? rOOTURL;
  String? gENERATEANDSENDOTP;
  String? lOGINWITHPASSWORD;
  String? rENEWACCESSTOKEN;
  String? uPDATEUSERPASSWORDWITHOTP;
  String? cHANGEUSERPASSWORD;
  String? vERIFYOTP;
  String? lOGOUT;
  String? gETWELCOMESCREENS;
  String? gETAPPRESOURCES;
  String? cHECKAPPUPDATE;
  String? dELETEREQUESTDATA;
  String? aCCOUNTDELETEREQUEST;
  String? uPDATEMYPROFILE;
  String? uPDATEDEVICEINFO;
  String? uPDATEMYPROFILEPIC;
  String? uPDATEFARMLANDALERTPIC;
  String? gETSTATES;
  String? gETSTATEREGIONS;
  String? gETREGIONAREAS;
  String? gETREGIONS;
  String? gETAREAS;
  String? gETAGENTBOTTOMBARMENU;
  String? gETAGENTPROFILEMENU;
  String? gETMYPROFILEDETAILS;
  String? gETAGENTANALYTICS;
  String? uPLOADPROFILEPICTURE;
  String? gETMYEARNINGS;
  String? gETMYCREDITS;
  String? gETNOTIFICATIONS;
  String? gETMYFARMLANDALERTS;
  String? gETMYFARMLANDS;
  String? gETMYFARMLEADS;
  String? cREATEFARMLANDALERT;
  String? uPDATEFARMLANDALERT;
  String? dELETEFARMLANDALERT;
  String? tRACKMYFARMLANDSTATUS;
  String? fARMLANDDISCOVERY;
  String? sEEALLFARMLANDS;
  String? gETGLCFARMLANDDETAILS;
  String? sEARCHFARMLANDS;
  String? sIMILARFARMLANDS;
  String? cOMPAREFARMLANDS;
  String? fAVORITEORUNFAVORITEFARMLAND;
  String? gETMYFAVORITEFARMLANDS;

  ApiEndPointsResponse(
      {this.rOOTURL,
      this.gENERATEANDSENDOTP,
      this.lOGINWITHPASSWORD,
      this.rENEWACCESSTOKEN,
      this.uPDATEUSERPASSWORDWITHOTP,
      this.cHANGEUSERPASSWORD,
      this.vERIFYOTP,
      this.lOGOUT,
      this.gETWELCOMESCREENS,
      this.gETAPPRESOURCES,
      this.cHECKAPPUPDATE,
      this.dELETEREQUESTDATA,
      this.aCCOUNTDELETEREQUEST,
      this.uPDATEMYPROFILE,
      this.uPDATEDEVICEINFO,
      this.uPDATEMYPROFILEPIC,
      this.uPDATEFARMLANDALERTPIC,
      this.gETSTATES,
      this.gETSTATEREGIONS,
      this.gETREGIONAREAS,
      this.gETREGIONS,
      this.gETAREAS,
      this.gETAGENTBOTTOMBARMENU,
      this.gETAGENTPROFILEMENU,
      this.gETMYPROFILEDETAILS,
      this.gETAGENTANALYTICS,
      this.uPLOADPROFILEPICTURE,
      this.gETMYEARNINGS,
      this.gETMYCREDITS,
      this.gETNOTIFICATIONS,
      this.gETMYFARMLANDALERTS,
      this.gETMYFARMLANDS,
      this.gETMYFARMLEADS,
      this.cREATEFARMLANDALERT,
      this.uPDATEFARMLANDALERT,
      this.dELETEFARMLANDALERT,
      this.tRACKMYFARMLANDSTATUS,
      this.fARMLANDDISCOVERY,
      this.sEEALLFARMLANDS,
      this.gETGLCFARMLANDDETAILS,
      this.sEARCHFARMLANDS,
      this.sIMILARFARMLANDS,
      this.cOMPAREFARMLANDS,
      this.fAVORITEORUNFAVORITEFARMLAND,
      this.gETMYFAVORITEFARMLANDS});

  ApiEndPointsResponse.fromJson(Map<String, dynamic> json) {
    rOOTURL = json['ROOT_URL'];
    gENERATEANDSENDOTP = json['GENERATE_AND_SEND_OTP'];
    lOGINWITHPASSWORD = json['LOGIN_WITH_PASSWORD'];
    rENEWACCESSTOKEN = json['RENEW_ACCESS_TOKEN'];
    uPDATEUSERPASSWORDWITHOTP = json['UPDATE_USER_PASSWORD_WITH_OTP'];
    cHANGEUSERPASSWORD = json['CHANGE_USER_PASSWORD'];
    vERIFYOTP = json['VERIFY_OTP'];
    lOGOUT = json['LOGOUT'];
    gETWELCOMESCREENS = json['GET_WELCOME_SCREENS'];
    gETAPPRESOURCES = json['GET_APP_RESOURCES'];
    cHECKAPPUPDATE = json['CHECK_APP_UPDATE'];
    dELETEREQUESTDATA = json['DELETE_REQUEST_DATA'];
    aCCOUNTDELETEREQUEST = json['ACCOUNT_DELETE_REQUEST'];
    uPDATEMYPROFILE = json['UPDATE_MY_PROFILE'];
    uPDATEDEVICEINFO = json['UPDATE_DEVICE_INFO'];
    uPDATEMYPROFILEPIC = json['UPDATE_MY_PROFILE_PIC'];
    uPDATEFARMLANDALERTPIC = json['UPDATE_FARMLAND_ALERT_PIC'];
    gETSTATES = json['GET_STATES'];
    gETSTATEREGIONS = json['GET_STATE_REGIONS'];
    gETREGIONAREAS = json['GET_REGION_AREAS'];
    gETREGIONS = json['GET_REGIONS'];
    gETAREAS = json['GET_AREAS'];
    gETAGENTBOTTOMBARMENU = json['GET_AGENT_BOTTOM_BAR_MENU'];
    gETAGENTPROFILEMENU = json['GET_AGENT_PROFILE_MENU'];
    gETMYPROFILEDETAILS = json['GET_MY_PROFILE_DETAILS'];
    gETAGENTANALYTICS = json['GET_AGENT_ANALYTICS'];
    uPLOADPROFILEPICTURE = json['UPLOAD_PROFILE_PICTURE'];
    gETMYEARNINGS = json['GET_MY_EARNINGS'];
    gETMYCREDITS = json['GET_MY_CREDITS'];
    gETNOTIFICATIONS = json['GET_NOTIFICATIONS'];
    gETMYFARMLANDALERTS = json['GET_MY_FARMLAND_ALERTS'];
    gETMYFARMLANDS = json['GET_MY_FARMLANDS'];
    gETMYFARMLEADS = json['GET_MY_FARM_LEADS'];
    cREATEFARMLANDALERT = json['CREATE_FARMLAND_ALERT'];
    uPDATEFARMLANDALERT = json['UPDATE_FARMLAND_ALERT'];
    dELETEFARMLANDALERT = json['DELETE_FARMLAND_ALERT'];
    tRACKMYFARMLANDSTATUS = json['TRACK_MY_FARMLAND_STATUS'];
    fARMLANDDISCOVERY = json['FARMLAND_DISCOVERY'];
    sEEALLFARMLANDS = json['SEE_ALL_FARMLANDS'];
    gETGLCFARMLANDDETAILS = json['GET_GLC_FARMLAND_DETAILS'];
    sEARCHFARMLANDS = json['SEARCH_FARMLANDS'];
    sIMILARFARMLANDS = json['SIMILAR_FARMLANDS'];
    cOMPAREFARMLANDS = json['COMPARE_FARMLANDS'];
    fAVORITEORUNFAVORITEFARMLAND = json['FAVORITE_OR_UN_FAVORITE_FARMLAND'];
    gETMYFAVORITEFARMLANDS = json['GET_MY_FAVORITE_FARMLANDS'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['ROOT_URL'] = rOOTURL;
    data['GENERATE_AND_SEND_OTP'] = gENERATEANDSENDOTP;
    data['LOGIN_WITH_PASSWORD'] = lOGINWITHPASSWORD;
    data['RENEW_ACCESS_TOKEN'] = rENEWACCESSTOKEN;
    data['UPDATE_USER_PASSWORD_WITH_OTP'] = uPDATEUSERPASSWORDWITHOTP;
    data['CHANGE_USER_PASSWORD'] = cHANGEUSERPASSWORD;
    data['VERIFY_OTP'] = vERIFYOTP;
    data['LOGOUT'] = lOGOUT;
    data['GET_WELCOME_SCREENS'] = gETWELCOMESCREENS;
    data['GET_APP_RESOURCES'] = gETAPPRESOURCES;
    data['CHECK_APP_UPDATE'] = cHECKAPPUPDATE;
    data['DELETE_REQUEST_DATA'] = dELETEREQUESTDATA;
    data['ACCOUNT_DELETE_REQUEST'] = aCCOUNTDELETEREQUEST;
    data['UPDATE_MY_PROFILE'] = uPDATEMYPROFILE;
    data['UPDATE_DEVICE_INFO'] = uPDATEDEVICEINFO;
    data['UPDATE_MY_PROFILE_PIC'] = uPDATEMYPROFILEPIC;
    data['UPDATE_FARMLAND_ALERT_PIC'] = uPDATEFARMLANDALERTPIC;
    data['GET_STATES'] = gETSTATES;
    data['GET_STATE_REGIONS'] = gETSTATEREGIONS;
    data['GET_REGION_AREAS'] = gETREGIONAREAS;
    data['GET_REGIONS'] = gETREGIONS;
    data['GET_AREAS'] = gETAREAS;
    data['GET_AGENT_BOTTOM_BAR_MENU'] = gETAGENTBOTTOMBARMENU;
    data['GET_AGENT_PROFILE_MENU'] = gETAGENTPROFILEMENU;
    data['GET_MY_PROFILE_DETAILS'] = gETMYPROFILEDETAILS;
    data['GET_AGENT_ANALYTICS'] = gETAGENTANALYTICS;
    data['UPLOAD_PROFILE_PICTURE'] = uPLOADPROFILEPICTURE;
    data['GET_MY_EARNINGS'] = gETMYEARNINGS;
    data['GET_MY_CREDITS'] = gETMYCREDITS;
    data['GET_NOTIFICATIONS'] = gETNOTIFICATIONS;
    data['GET_MY_FARMLAND_ALERTS'] = gETMYFARMLANDALERTS;
    data['GET_MY_FARMLANDS'] = gETMYFARMLANDS;
    data['GET_MY_FARM_LEADS'] = gETMYFARMLEADS;
    data['CREATE_FARMLAND_ALERT'] = cREATEFARMLANDALERT;
    data['UPDATE_FARMLAND_ALERT'] = uPDATEFARMLANDALERT;
    data['DELETE_FARMLAND_ALERT'] = dELETEFARMLANDALERT;
    data['TRACK_MY_FARMLAND_STATUS'] = tRACKMYFARMLANDSTATUS;
    data['FARMLAND_DISCOVERY'] = fARMLANDDISCOVERY;
    data['SEE_ALL_FARMLANDS'] = sEEALLFARMLANDS;
    data['GET_GLC_FARMLAND_DETAILS'] = gETGLCFARMLANDDETAILS;
    data['SEARCH_FARMLANDS'] = sEARCHFARMLANDS;
    data['SIMILAR_FARMLANDS'] = sIMILARFARMLANDS;
    data['COMPARE_FARMLANDS'] = cOMPAREFARMLANDS;
    data['FAVORITE_OR_UN_FAVORITE_FARMLAND'] =
        fAVORITEORUNFAVORITEFARMLAND;
    data['GET_MY_FAVORITE_FARMLANDS'] = gETMYFAVORITEFARMLANDS;
    return data;
  }
}
