class EndpointsResponse {
  String? rOOTURL;
  String? gENERATEANDSENDOTP;
  String? lOGINWITHPASSWORD;
  String? rENEWACCESSTOKEN;
  String? uPDATEUSERPASSWORDWITHOTP;
  String? cHANGEUSERPASSWORD;
  String? vERIFYOTP;
  String? lOGOUT;
  String? gETWELCOMESCREENS;
  String? gETAPPRESOURCES;
  String? cHECKAPPUPDATE;
  String? dELETEREQUESTDATA;
  String? aCCOUNTDELETEREQUEST;
  String? uPDATEMYPROFILE;
  String? gETAGENTBOTTOMBARMENU;
  String? gETAGENTPROFILEMENU;
  String? gETMYPROFILEDETAILS;
  String? gETAGENTANALYTICS;
  String? uPLOADPROFILEPICTURE;
  String? gETMYEARNINGS;
  String? gETMYCREDITS;
  String? gETNOTIFICATIONS;
  String? gETMYFARMLANDALERTS;
  String? cREATEFARMLANDALERT;
  String? uPDATEFARMLANDALERT;
  String? dELETEFARMLANDALERT;
  String? gETMYFARMLANDS;
  String? gETMYFARMLANDDETAILS;
  String? tRACKMYFARMLANDSTATUS;
  String? cOMPAREFARMLANDS;
  String? gETGLCFARMLANDS;
  String? gETGLCFARMLANDDETAILS;
  String? sEARCHFARMLANDS;
  String? sEEALLFARMLANDS;
  String? lIKEANDUNLIKEFARMLAND;

  EndpointsResponse(
      {this.rOOTURL,
      this.gENERATEANDSENDOTP,
      this.lOGINWITHPASSWORD,
      this.rENEWACCESSTOKEN,
      this.uPDATEUSERPASSWORDWITHOTP,
      this.cHANGEUSERPASSWORD,
      this.vERIFYOTP,
      this.lOGOUT,
      this.gETWELCOMESCREENS,
      this.gETAPPRESOURCES,
      this.cHECKAPPUPDATE,
      this.dELETEREQUESTDATA,
      this.aCCOUNTDELETEREQUEST,
      this.uPDATEMYPROFILE,
      this.gETAGENTBOTTOMBARMENU,
      this.gETAGENTPROFILEMENU,
      this.gETMYPROFILEDETAILS,
      this.gETAGENTANALYTICS,
      this.uPLOADPROFILEPICTURE,
      this.gETMYEARNINGS,
      this.gETMYCREDITS,
      this.gETNOTIFICATIONS,
      this.gETMYFARMLANDALERTS,
      this.cREATEFARMLANDALERT,
      this.uPDATEFARMLANDALERT,
      this.dELETEFARMLANDALERT,
      this.gETMYFARMLANDS,
      this.gETMYFARMLANDDETAILS,
      this.tRACKMYFARMLANDSTATUS,
      this.cOMPAREFARMLANDS,
      this.gETGLCFARMLANDS,
      this.gETGLCFARMLANDDETAILS,
      this.sEARCHFARMLANDS,
      this.sEEALLFARMLANDS,
      this.lIKEANDUNLIKEFARMLAND});

  EndpointsResponse.fromJson(Map<String, dynamic> json) {
    rOOTURL = json['ROOT_URL'];
    gENERATEANDSENDOTP = json['GENERATE_AND_SEND_OTP'];
    lOGINWITHPASSWORD = json['LOGIN_WITH_PASSWORD'];
    rENEWACCESSTOKEN = json['RENEW_ACCESS_TOKEN'];
    uPDATEUSERPASSWORDWITHOTP = json['UPDATE_USER_PASSWORD_WITH_OTP'];
    cHANGEUSERPASSWORD = json['CHANGE_USER_PASSWORD'];
    vERIFYOTP = json['VERIFY_OTP'];
    lOGOUT = json['LOGOUT'];
    gETWELCOMESCREENS = json['GET_WELCOME_SCREENS'];
    gETAPPRESOURCES = json['GET_APP_RESOURCES'];
    cHECKAPPUPDATE = json['CHECK_APP_UPDATE'];
    dELETEREQUESTDATA = json['DELETE_REQUEST_DATA'];
    aCCOUNTDELETEREQUEST = json['ACCOUNT_DELETE_REQUEST'];
    uPDATEMYPROFILE = json['UPDATE_MY_PROFILE'];
    gETAGENTBOTTOMBARMENU = json['GET_AGENT_BOTTOM_BAR_MENU'];
    gETAGENTPROFILEMENU = json['GET_AGENT_PROFILE_MENU'];
    gETMYPROFILEDETAILS = json['GET_MY_PROFILE_DETAILS'];
    gETAGENTANALYTICS = json['GET_AGENT_ANALYTICS'];
    uPLOADPROFILEPICTURE = json['UPLOAD_PROFILE_PICTURE'];
    gETMYEARNINGS = json['GET_MY_EARNINGS'];
    gETMYCREDITS = json['GET_MY_CREDITS'];
    gETNOTIFICATIONS = json['GET_NOTIFICATIONS'];
    gETMYFARMLANDALERTS = json['GET_MY_FARMLAND_ALERTS'];
    cREATEFARMLANDALERT = json['CREATE_FARMLAND_ALERT'];
    uPDATEFARMLANDALERT = json['UPDATE_FARMLAND_ALERT'];
    dELETEFARMLANDALERT = json['DELETE_FARMLAND_ALERT'];
    gETMYFARMLANDS = json['GET_MY_FARMLANDS'];
    gETMYFARMLANDDETAILS = json['GET_MY_FARMLAND_DETAILS'];
    tRACKMYFARMLANDSTATUS = json['TRACK_MY_FARMLAND_STATUS'];
    cOMPAREFARMLANDS = json['COMPARE_FARMLANDS'];
    gETGLCFARMLANDS = json['GET_GLC_FARMLANDS'];
    gETGLCFARMLANDDETAILS = json['GET_GLC_FARMLAND_DETAILS'];
    sEARCHFARMLANDS = json['SEARCH_FARMLANDS'];
    sEEALLFARMLANDS = json['SEE_ALL_FARMLANDS'];
    lIKEANDUNLIKEFARMLAND = json['LIKE_AND_UNLIKE_FARMLAND'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['ROOT_URL'] = this.rOOTURL;
    data['GENERATE_AND_SEND_OTP'] = this.gENERATEANDSENDOTP;
    data['LOGIN_WITH_PASSWORD'] = this.lOGINWITHPASSWORD;
    data['RENEW_ACCESS_TOKEN'] = this.rENEWACCESSTOKEN;
    data['UPDATE_USER_PASSWORD_WITH_OTP'] = this.uPDATEUSERPASSWORDWITHOTP;
    data['CHANGE_USER_PASSWORD'] = this.cHANGEUSERPASSWORD;
    data['VERIFY_OTP'] = this.vERIFYOTP;
    data['LOGOUT'] = this.lOGOUT;
    data['GET_WELCOME_SCREENS'] = this.gETWELCOMESCREENS;
    data['GET_APP_RESOURCES'] = this.gETAPPRESOURCES;
    data['CHECK_APP_UPDATE'] = this.cHECKAPPUPDATE;
    data['DELETE_REQUEST_DATA'] = this.dELETEREQUESTDATA;
    data['ACCOUNT_DELETE_REQUEST'] = this.aCCOUNTDELETEREQUEST;
    data['UPDATE_MY_PROFILE'] = this.uPDATEMYPROFILE;
    data['GET_AGENT_BOTTOM_BAR_MENU'] = this.gETAGENTBOTTOMBARMENU;
    data['GET_AGENT_PROFILE_MENU'] = this.gETAGENTPROFILEMENU;
    data['GET_MY_PROFILE_DETAILS'] = this.gETMYPROFILEDETAILS;
    data['GET_AGENT_ANALYTICS'] = this.gETAGENTANALYTICS;
    data['UPLOAD_PROFILE_PICTURE'] = this.uPLOADPROFILEPICTURE;
    data['GET_MY_EARNINGS'] = this.gETMYEARNINGS;
    data['GET_MY_CREDITS'] = this.gETMYCREDITS;
    data['GET_NOTIFICATIONS'] = this.gETNOTIFICATIONS;
    data['GET_MY_FARMLAND_ALERTS'] = this.gETMYFARMLANDALERTS;
    data['CREATE_FARMLAND_ALERT'] = this.cREATEFARMLANDALERT;
    data['UPDATE_FARMLAND_ALERT'] = this.uPDATEFARMLANDALERT;
    data['DELETE_FARMLAND_ALERT'] = this.dELETEFARMLANDALERT;
    data['GET_MY_FARMLANDS'] = this.gETMYFARMLANDS;
    data['GET_MY_FARMLAND_DETAILS'] = this.gETMYFARMLANDDETAILS;
    data['TRACK_MY_FARMLAND_STATUS'] = this.tRACKMYFARMLANDSTATUS;
    data['COMPARE_FARMLANDS'] = this.cOMPAREFARMLANDS;
    data['GET_GLC_FARMLANDS'] = this.gETGLCFARMLANDS;
    data['GET_GLC_FARMLAND_DETAILS'] = this.gETGLCFARMLANDDETAILS;
    data['SEARCH_FARMLANDS'] = this.sEARCHFARMLANDS;
    data['SEE_ALL_FARMLANDS'] = this.sEEALLFARMLANDS;
    data['LIKE_AND_UNLIKE_FARMLAND'] = this.lIKEANDUNLIKEFARMLAND;
    return data;
  }
}
